### ISSUE TITLE
Fix the build please

### ISSUE THREAD

**Issue by megakoresh** [mikermcneil/machinepack-azure#10]
It's [failing](https://travis-ci.org/mikermcneil/machinepack-azure/jobs/82971564), and the machinepack is unusable... Getting that same error when trying to run `sails-deploy`
NPM version is 3.3.9 BTW, so install is flat. Maybe that's the issue? It did work with a flat install less than a month ago though.

**Comment by megakoresh** [comment]
Pffft....
It's that [last edit you made](https://github.com/mikermcneil/machinepack-azure/commit/45f53d1e994d2f79842f7b3546c86a195f3134b3), Felix...
![really, noone used it until me?](http://images.devs-on.net/Image/XzzC2rcTjq40E2AX-Region.png)
Them sneaky semicolons.

**Comment by felixrieseberg** [comment]
Thanks for telling us! Fixed :)
