### ISSUE TITLE
Unable to install because of VS dependency conflicts

### ISSUE THREAD

**Issue by mbcooper** [mikermcneil/machinepack-azure#6]
I attempted to install but ran into a build error.
I am up to date on VS 2013, and have had 2012 and perhaps 2010 installed.  I also re-installed the VS 2010 SDK, but to no help ...

```
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please install Visual Studio 2
010 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution...". [E:\src\sailng\node_modules\machinepack-azure\node_modules\azure-cli\node_
modules\streamline\node_modules\fibers\build\fibers.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
```

**Comment by sedouard** [comment]
Hey @mbcooper silly question but are you doing `npm install` within a visual studio developer command prompt?

**Comment by mbcooper** [comment]
@sedouard nope.  terminal on Windows 8.1

**Comment by sedouard** [comment]
@mbcooper try using the dev command prompt. it has all the build tools on PATH.

**Comment by felixrieseberg** [comment]
Thanks for reporting! @sedouard: I'm not even sure that we really, really need fibers. I can't think of any thread-heavy work that we're doing, so maybe we just kick out the module that needs it.

**Comment by sedouard** [comment]
It's `azure-cli`. If you remember my [PR](https://github.com/mikermcneil/sails-deploy-azure/commit/0628defc38c08dfbc5decdde9a3382b8949428ad) into `sails-deploy-azure` it was specifically because of this (the build failed on azure websites).

We can't really get rid of this module of course or literally nothing would work :-).

**Comment by felixrieseberg** [comment]
_shakes fist at azure-cli_. 

@mbcooper: See if using the right shell helps you.

**Comment by mbcooper** [comment]
@felixrieseberg ?right shell?  not sure I follow.  Im doing this dev in WebStorm.  I just open up a terminal and npm ...
So what are you suggesting ??  I'd love to get this to work!

**Comment by mbcooper** [comment]
Ah -- i also tried

```
npm install azure-cli -g
```

and that was what causes the crash

**Comment by sedouard** [comment]
yeah, its that module that's causing problems because it can't find you build tools. Search in windows for `visual studio developer command prompt`. Then execute the same command in that shell. It will have you build tools on your path and the build should hopefully succeed.

**Comment by mbcooper** [comment]
OK - just run from VS?

**Comment by mbcooper** [comment]
No dice.  ran from 2013, and it complained as follows:

```
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build tools for Visual Studio 2010 (P
latform Toolset = 'v100') cannot be found. To build using the v100 build tools, please install Visual Studio 2010 build tools.  Alternatively, you ma
y upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution...". [C:
\Users\mike\AppData\Roaming\npm\node_modules\azure-cli\node_modules\streamline\node_modules\fibers\build\fibers.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
```

Ran it from VS 2010, and it complained the same, as I have 2013, which has overloaded the 2010 tools.

Grrrrrr.....

**Comment by mbcooper** [comment]
OK - Larry Franks at microsoft gave me the following:

> If you have a version of Visual Studio on the machine, like 2012 or 2013, you can also try the --msvs_version parameter to specify the version you have. For example, npm install azure-cli -g --msvs_version=2012

Worked like a charm.  Allowed me to install azure-cli from my VS 2013 prompt.  Now let' see if I can get  the same notion to work for the machine pack.

**Comment by sedouard** [comment]
oh nice I didn't know gyp took that parameter. if you can get `azure-cli` installed the machine pack should work just fine.

**Comment by mbcooper** [comment]
yep.  I was finally able to do the following ..

```
npm install machinepack-azure --save --msvs_version=2013
```
