### ISSUE TITLE
Please fix the filename path issue for windows that prevents webjobs from being uploaded

### ISSUE THREAD

**Issue by megakoresh** [mikermcneil/machinepack-azure#9]
[Referencing this issue for the `sails-deploy-azure` strategy](https://github.com/mikermcneil/sails-deploy-azure/issues/12), I found the problem that was causing it, and it's in this machinepack. The edit itself is too trivial for me to clone the whole repo, so can someone who has it just make the edit? Just change the path separator from `/` to `\\` as per Windows standard. Here's the picture with all the info you need:
![What to edit and where](https://camo.githubusercontent.com/0be713e7c8f51ec7fe0906842a609b91610cb743/687474703a2f2f692e696d6775722e636f6d2f6233325a6c324f2e706e67)

**Comment by felixrieseberg** [comment]
Thanks for the detailed report! I fixed the issue in the repo, but @mikermcneil would have to push it up to npm (for both packages, please - just run `npm publish ./`, the correct version numbers are already on GitHub). In the meantime, simply install `sails-azure-deploy` using npm's GitHub installation method:

```
{
"dependencies": {
    "sails-deploy-azure": "mikermcneil/sails-deploy-azure#0f3ea43c60ed2149d3e292fa4472e668c33cbd24"
  }
}
```

**Comment by mikermcneil** [comment]
@felixrieseberg @megakoresh thanks guys-- done and done

**Comment by mikermcneil** [comment]
@felixrieseberg looks like this one is @sedouard on npm actually (I'm not on it).  I must have `npm owner add`ed you on sails-deploy-azure  (I'll add Steve on that one too)

**Comment by mikermcneil** [comment]
:heavy_check_mark: 

![screen shot 2015-10-27 at 8 35 01 am](https://cloud.githubusercontent.com/assets/618009/10759511/aa47b088-7c85-11e5-8df9-3706a2221e37.png)

**Comment by felixrieseberg** [comment]
Huh, thanks!

@sedouard: Please add me and/or publish. Thanks!

**Comment by sedouard** [comment]
For some crazy reason, I can't do `npm login` (and therefore `npm publish` doesn't work). It just fails with an unknown error. @felixrieseberg I've added you to the package so you should be able to publish.

**Comment by felixrieseberg** [comment]
And done!
